language: python
python:
  - "3.7"
services:
  - docker
before_install:
  - docker build -f docker/dockerfile -t chimbuko/vis .
install:
  - pip install --upgrade pip
script: docker run -it chimbuko/vis bash -c "python3 tests/new_sharded_provdb_test.py"