language: python
python:
  - "3.7"
services:
  - docker
before_install:
  - docker build -f docker/dockerfile -t chimbuko/vis .
script: docker run -p 8080:5002 -it chimbuko/vis --cap-add=SYS_PTRACE --security-opt seccomp=unconfined